# Generated by Django 4.0.4 on 2022-04-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PR', 'Private'), ('PU', 'Public')], default='DR', max_length=2)),
            ],
        ),
    ]
